name: Rollback

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  rollback:
    if: ${{ vars.DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Tag the previous Docker image as the latest
        run: |
          PREVIOUS_TAG=${{ steps.previoustag.outputs.tag }}
          PREVIOUS_TAG_WITHOUT_V=${PREVIOUS_TAG#v}

          docker pull ghcr.io/${{ github.repository }}:$PREVIOUS_TAG_WITHOUT_V
          docker tag ghcr.io/${{ github.repository }}:$PREVIOUS_TAG_WITHOUT_V ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

  rollback-deploy:
    if: ${{ vars.DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    needs: rollback
    steps:
      - name: Rollback the app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "${{ secrets.PASSWORD }}" | sudo -S sh -c "
            cd school_464 &&
            docker compose -f docker-compose.prod.yml up django --force-recreate -d &&
            docker image prune -f
            "
